name: the_second_chapter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/logo.png

  fonts:
    - family: Otomanopee
      fonts:
      - asset: fonts/OtomanopeeOne-Regular.ttf
    - family: Lato
      fonts:
      - asset: fonts/Lato-Regular.ttf


